version: "3.8"

services:
  meu-fastapi: # nome do servi√ßo (pode mudar)
    image: ghcr.io/matheusdea/rev-fastapi:latest # imagem do GitHub
    networks:
      - portainer
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure
      labels:
        - "traefik.enable=true"
        - "traefik.http.routers.meu-fastapi.rule=Host(`fastapi.revenuelab.com.br`)"
        - "traefik.http.routers.meu-fastapi.entrypoints=websecure"
        - "traefik.http.routers.meu-fastapi.tls.certresolver=letsencryptresolver"
        - "traefik.http.services.meu-fastapi.loadbalancer.server.port=8000"

networks:
  portainer:
    external: true
